### ISSUE TITLE
check robots.txt to allow an instance to opt out

### ISSUE THREAD

**Issue by tyrm** [g3rv4/GetMoarFediverse#12]

**Comment by g3rv4** [comment]
what is what the instance would be opting out of? getting its `/tags/{tag}.json` scraped?

I'd gladly implement that, but:

* If your posts are on the federated timeline of a big instance, it would be included
* Anyone can download the source code, remove the check, and run it without the `robots.txt` check

If you confirm that checking the `robots.txt` before getting the content from `/tags/{tag}.json` is something you consider a valuable thing, I'd be glad to add it

**Comment by tyrm** [comment]
yes, this is important as it continues the idea people should have the option to choose. 

i personally don't agree with the argument that, because someone could modify the code to use it maliciously, i shouldn't even bother.

**Comment by g3rv4** [comment]
awesome, working on it :)

**Comment by g3rv4** [comment]
addressed this on #17 (and released it on [version 1.0.28](https://github.com/g3rv4/GetMoarFediverse/releases/tag/v1.0.28)).

If you want to update your `robots.txt`, I'd love to triple check it's not pulling data from your instance.

**Comment by g3rv4** [comment]
@tyrm I'm closing this as completed, but if you find issues with it feel free to reopen it.
