### ISSUE TITLE
Provide a count of posts pulled for each hashtag from each server

### ISSUE THREAD

**Issue by jlindborg** [g3rv4/GetMoarFediverse#2]
Currently it lists which hashtag it's searching each server for - it'd be nice if this output included how many matching posts were found on each server for each hashtag so you can see how much value you're getting out of a particular server.

**Comment by g3rv4** [comment]
Can you take 1.0.31 for a spin? I've added reports of how many new statuses it pulls from each server/tag and then how many remain after removing duplicates

**Comment by jlindborg** [comment]
perfect - very useful info.  thanks
