### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by quicoto** [g3rv4/GetMoarFediverse#41]
Since this morning I'm getting the same error in my GitHub Actions runs

https://github.com/quicoto/mastodon-HashtagsPull/actions/runs/5240507632/jobs/9461437086

Any idea what could it be?

Thank you

**Comment by quicoto** [comment]
Now it works 🤷‍♂️ 

https://github.com/quicoto/mastodon-HashtagsPull/actions/runs/5240772157/jobs/9462012472

**Comment by g3rv4** [comment]
I see what happened, one of the instances you're pulling hashtags from was not returning json when GMF expected it to. I'll handle the exception with details as to which is the instance failing :)

**Comment by quicoto** [comment]
Wonderful, thank you very much
