### ISSUE TITLE
will this continue to work in 4.2.0?

### ISSUE THREAD

**Issue by quicoto** [g3rv4/GetMoarFediverse#43]
With the upcoming change about the streaming API, will this still work?

I'm unaware if we make use is that API die fetching posts 

https://github.com/mastodon/mastodon/pull/23989

**Comment by g3rv4** [comment]
yup, it's using the [timelines/tags](https://docs.joinmastodon.org/methods/timelines/#tag) api method which keeps on working on 4.2.0. mastodon.social is running 4.2.0 and [this ur](https://mastodon.social/api/v1/timelines/tag/mastoadmins) still works :)

**Comment by quicoto** [comment]
Sweet! Thank you very much
