### ISSUE TITLE
Docker and GitHub Action Failed on Unhandled exception (Parameter 'MaxDegreeOfParallelism')

### ISSUE THREAD

**Issue by tylernguyen** [g3rv4/GetMoarFediverse#44]
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'MaxDegreeOfParallelism')
   at System.Threading.Tasks.ParallelOptions.set_MaxDegreeOfParallelism(Int32 )
   at Program.<Main>$(String[] args) in /var/src/Program.cs:line 91
   at Program.<Main>(String[] args)
``` 
I get the same error above when running through the Docker container and GitHub Action workflow alike.

This is with `config.json` pointing to the Mastodon API with read:follows scope only.

- Mastodon 4.2.0
- :latest Docker container tag

**Comment by g3rv4** [comment]
Does the user that owns the token follow any tags?

**Comment by tylernguyen** [comment]
> Does the user that owns the token follow any tags?

!!!

That was the issue. Everything seems to run fine once I've following some tags.
