### ISSUE TITLE
Video tutorial gone

### ISSUE THREAD

**Issue by p37307** [g3rv4/GetMoarFediverse#52]
On the main [readme](https://github.com/g3rv4/GetMoarFediverse/blob/main/README.md), at section _What about Docker on Windows?,_ _You can watch this demo by Jeff Lindborg_ (https://www.youtube.com/watch?v=v73ZKtP0rzE), YouTube is saying the video is no longer available. 

Just thought you would want to know so you can adjust.

**Comment by g3rv4** [comment]
thanks!
